spring:
  cloud:
    loadbalancer:
      cache:
        enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.uri:localhost:8761}/eureka/

jwt:
  secret: 653F65CCFD82585F3983825EDA89D123
  expiration: 86400
